### ISSUE TITLE
PX Submission tool : Installation problem

### ISSUE THREAD

**Issue by deeptijk** [PRIDE-Archive/pride-curation-scripts#10]
There is some issue reported in installing the PX Submission tool. 
Errors -

"Could not find the main class: uk.ac.ebi.pride.AppBootstrap. Program will exit."

and 
"Exception in thread "main" java.lang.UnsupportedClassVersionError: uk/ac/ebi/pride/AppBootstrap : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)"

This is the ticket - https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=324054

**Comment by sureshhewabi** [comment]
1) You should unzip the zipped file and run px-submission-tool-2.4.10.jar, not the zipped file
2) Make sure you have not put the tool in a directory with a blank space or similar
3) Please open a command line window and run following command to check your java version:
 java -version

**Comment by sureshhewabi** [comment]
If you see "java.lang.UnsupportedClassVersionError", that means user is not using java version 1.8 or higher. Please ask them to verify version by command "java -version". Currently, latest Px submission tool(2.4.10) requires at least java 1.8 version

**Comment by sureshhewabi** [comment]
These pages helps you to install different java versions and quickly shift to different versions and test the tools without worring about the JAVA_HOMES:

- http://www.jenv.be
- https://www.javacodegeeks.com/2017/04/setting-multiple-java-jre-jdk-macosx-using-brew-cask-jenv.html

This is only for mac users. Also 1.7 java version should be installed manually.

**Comment by deeptijk** [comment]
Thanks.
