### ISSUE TITLE
Submission PX file Error

### ISSUE THREAD

**Issue by deeptijk** [PRIDE-Archive/pride-curation-scripts#12]
```
log/validation/1-20190221-5001-RESUB1-validation.log

Got an Error:

Updating file paths in /nfs/pride/prod/archive/1-20190221-5001-RESUB1/internal/submission.px
Encountered an error executing the step
java.lang.ArrayIndexOutOfBoundsException: 8
        at uk.ac.ebi.pride.data.io.SubmissionFileParser.parseSampleMetadata(SubmissionFileParser.java:483)
        at uk.ac.ebi.pride.data.io.SubmissionFileParser.parse(SubmissionFileParser.java:152)
        at uk.ac.ebi.pride.data.io.SubmissionFileParser.parse(SubmissionFileParser.java:56)
        at uk.ac.ebi.pride.tasklet.file.UpdateSubmissionSummaryFilePathTasklet.execute(UpdateSubmissionSummaryFilePathTasklet.java:39)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:132)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:120)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy54.execute(Unknown Source)
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:395)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:131)
        at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:267)
        at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:77)
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368)
        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
        at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:253)
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:195)
        at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:137)
        at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64)
        at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:60)
        at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:152)
        at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:131)
        at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:135)
        at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:301)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:134)
        at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:49)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:127)
        at org.springframework.batch.core.launch.support.CommandLineJobRunner.start(CommandLineJobRunner.java:351)
        at org.springframework.batch.core.launch.support.CommandLineJobRunner.main(CommandLineJobRunner.java:577)
StepExecution - updateSubmissionStep ends at: 2019-02-22 13:22:47.462
===================================================================================
Job exit status: FAILED
Number of exceptions 1

```

**Comment by sureshhewabi** [comment]
I locally downloaded the submission.px file and tested. I found that line number 36 header has 10 columns, but the last line which is line number 37 has only 8 columns. This is because last two tabs are missing in this line. You need to add two tabs at the end if the last line(37). You might need to use VIM editor, because some IDEs try to remove tabs automatically.

![screen shot 2019-02-25 at 09 26 58](https://user-images.githubusercontent.com/5387193/53331088-fd502680-38e7-11e9-9ab6-473897c492d6.png)
![screen shot 2019-02-25 at 09 27 14](https://user-images.githubusercontent.com/5387193/53331089-fd502680-38e7-11e9-9574-7abf0b758455.png)

`vi submission.px`
Go to insert mode `i` and navigate to last line
press two tab characters
`:wq`

**Comment by deeptijk** [comment]
I tried as suggested but got an error - 
Experimental factor cannot be empty: 39

 Ticket - 1-20190221-5001-RESUB2

**Comment by sureshhewabi** [comment]
I have had a look on several PX files, and I found that if Experimental factor is not available, it should have the value as “Not available”.

**Comment by sureshhewabi** [comment]
With the latest version of submission tool 2.4.10, if we do not provide value for experimental factor, tool  will insert the value as "Not provided". In this case, may be user has used an old version of PX tool

**Comment by sureshhewabi** [comment]
@deeptijk is this sorted out?

**Comment by sureshhewabi** [comment]
I think this is sorted out now. If required you can reopen
